WITH FormattedData AS (
    SELECT DISTINCT
        CONCAT(
            s.itemid COLLATE DATABASE_DEFAULT, '-', 
            sDim.INVENTSIZEID COLLATE DATABASE_DEFAULT, '-', 
            sDim.INVENTCOLORID COLLATE DATABASE_DEFAULT
        ) AS FormattedItemID,
        p.RETAILVARIANTID
    FROM INVENTSUM AS s
    JOIN INVENTDIM AS sDim 
        ON sDim.InventDimId COLLATE DATABASE_DEFAULT = s.InventDimId COLLATE DATABASE_DEFAULT
    JOIN INVENTDIM AS pDim 
        ON pDim.INVENTCOLORID COLLATE DATABASE_DEFAULT = sDim.INVENTCOLORID COLLATE DATABASE_DEFAULT
        AND pDim.INVENTSIZEID COLLATE DATABASE_DEFAULT = sDim.INVENTSIZEID COLLATE DATABASE_DEFAULT
        AND pDim.DATAAREAID COLLATE DATABASE_DEFAULT = sDim.DATAAREAID COLLATE DATABASE_DEFAULT
    JOIN INVENTDIMCOMBINATION AS p 
        ON p.INVENTDIMID COLLATE DATABASE_DEFAULT = pDim.INVENTDIMID COLLATE DATABASE_DEFAULT
        AND p.ITEMID COLLATE DATABASE_DEFAULT = s.ITEMID COLLATE DATABASE_DEFAULT
)
SELECT * FROM FormattedData
WHERE FormattedItemID COLLATE DATABASE_DEFAULT IN ('')
