SELECT
    sDim.INVENTLOCATIONID,
    SUM(s.physicalinvent) AS [NET ON HAND D365]
FROM INVENTSUM AS s
JOIN INVENTDIM AS sDim 
    ON sDim.InventDimId = s.InventDimId
JOIN INVENTDIM AS pDim 
    ON pDim.INVENTCOLORID = sDim.INVENTCOLORID
    AND pDim.INVENTSIZEID = sDim.INVENTSIZEID
    AND pDim.DATAAREAID = sDim.DATAAREAID
JOIN INVENTDIMCOMBINATION AS p 
    ON p.INVENTDIMID = pDim.INVENTDIMID
    AND p.ITEMID = s.ITEMID
GROUP BY 
    sDim.INVENTLOCATIONID
ORDER BY 
    sDim.INVENTLOCATIONID ASC;
