SELECT 
    sum(s.AVAILPHYSICAL)
FROM INVENTSUM AS s
JOIN INVENTDIM AS sDim 
    ON sDim.INVENTDIMID = s.INVENTDIMID
    AND sDim.DATAAREAID = s.DATAAREAID
JOIN INVENTDIM AS pDim 
    ON pDim.INVENTCOLORID = sDim.INVENTCOLORID
    AND pDim.INVENTSIZEID = sDim.INVENTSIZEID
    AND pDim.DATAAREAID = sDim.DATAAREAID
JOIN INVENTDIMCOMBINATION AS p 
    ON p.INVENTDIMID = pDim.INVENTDIMID
    AND p.ITEMID = s.ITEMID
    AND p.DATAAREAID = sDim.DATAAREAID
JOIN INVENTTABLE AS it
    ON p.ITEMID = it.ITEMID
    AND p.DATAAREAID = it.DATAAREAID 
WHERE sDim.INVENTLOCATIONID = '0220'
    AND s.AVAILPHYSICAL >= 1
    AND p.pacProductMarkdownTypeId = 'MD'
    AND it.SUNTAFCATEGORYVALUE IN ('011', '012', '013', '014');
