SELECT 
    s.itemid,
    p.RETAILVARIANTID, 
    s.physicalinvent

FROM INVENTSUM AS s
JOIN INVENTDIM AS sDim 
    ON sDim.InventDimId = s.InventDimId
JOIN INVENTDIM AS pDim 
    ON pDim.INVENTCOLORID = sDim.INVENTCOLORID
    AND pDim.INVENTSIZEID = sDim.INVENTSIZEID
    AND pDim.DATAAREAID = sDim.DATAAREAID
JOIN INVENTDIMCOMBINATION AS p 
    ON p.INVENTDIMID = pDim.INVENTDIMID
    AND p.ITEMID = s.ITEMID
WHERE sDim.INVENTLOCATIONID = '0003'
