-- Robling DWH_F_INV_ILD_B retail valuation at 4905 (LOC_KEY 27100003).
-- F_OH_RTL is stored, not computed by the view. Restatements do NOT bump RCD_UPD_TS, and
-- time-travel retention is 1 day, so capture snapshots if you need to prove a change.
-- END_DAY_KEY is inclusive.

-- 1) Days at each unit retail per SKU since 7/1
SELECT ITM_KEY, ROUND(F_OH_RTL / F_OH_QTY, 2) AS UNIT_RTL,
       SUM(DATEDIFF(day, GREATEST(DAY_KEY, '2026-07-01'::date), LEAST(END_DAY_KEY, CURRENT_DATE())) + 1) AS DAYS,
       MIN(GREATEST(DAY_KEY, '2026-07-01'::date)) AS FIRST_DAY,
       MAX(LEAST(END_DAY_KEY, CURRENT_DATE())) AS LAST_DAY
FROM ROBLING_PRD_DB.DW_DWH.DWH_F_INV_ILD_B
WHERE LOC_KEY = 27100003 AND END_DAY_KEY >= '2026-07-01' AND F_OH_QTY > 0
GROUP BY 1, 2;

-- 2) Current open row + 9/21 row + item keys
SELECT i.ITM_KEY, i.DAY_KEY AS OPEN_DAY_KEY, i.F_OH_QTY AS CUR_OH_QTY, i.F_OH_RTL AS CUR_OH_RTL, i.F_OH_CST AS CUR_OH_CST,
       r.F_OH_QTY AS QTY_0921, r.F_OH_RTL AS RTL_0921,
       l.IP_SKU_DISPLAYNUM, l.IP_SHORT_SKU, l.ITM_DESC
FROM ROBLING_PRD_DB.DW_DWH.DWH_F_INV_ILD_B i
LEFT JOIN ROBLING_PRD_DB.DW_DWH.DWH_F_INV_ILD_B r
       ON r.ITM_KEY = i.ITM_KEY AND r.LOC_KEY = 27100003 AND r.DAY_KEY <= '2026-09-21' AND r.END_DAY_KEY >= '2026-09-21'
JOIN ROBLING_PRD_DB.DW_DWH_V.V_DWH_D_PRD_ITM_LU l ON l.ITM_KEY = i.ITM_KEY
WHERE i.LOC_KEY = 27100003 AND i.END_DAY_KEY = '9999-12-31';

-- 3) Latest Robling price-log book retail at 4905
SELECT ITM_KEY, IP_NEW_BOOK_RETAIL AS LOG_BOOK_RETAIL, IP_EFF_DATE::date AS LOG_EFF_DATE
FROM ROBLING_PRD_DB.DW_DWH.IP_DWH_R_MD_SKU_PRICE_D
WHERE LOC_KEY = 27100003
QUALIFY ROW_NUMBER() OVER (PARTITION BY ITM_KEY ORDER BY IP_EFF_DATE DESC, RCD_UPD_TS DESC) = 1;
